version: "3.3"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=automaton
      - MYSQL_PASSWORD=automaton
      - MYSQL_DATABASE=automaton
