export const API_ENDPOINT = process.env.REACT_APP_API_ENDPOINT;
export const GOOGLE_OPEN_ID_CONNECT_ENDPOINT =
  process.env.REACT_APP_GOOGLE_OPEN_ID_CONNECT_ENDPOINT;
export const GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID;
export const GOOGLE_OPEN_ID_CONNECT_REDIRECT_URI = process.env.REACT_APP_GOOGLE_OPEN_ID_CONNECT_REDIRECT_URI;

export const REACT_APP_TWITTER_OAUTH_ENDPOINT = process.env.REACT_APP_TWITTER_OAUTH_ENDPOINT;

export const REACT_APP_GATAG_ID = process.env.REACT_APP_GATAG_ID;

export const CONTACT_EMAIL = process.env.REACT_APP_CONTACT_EMAIL;
export const GIT_REPOSITORY_URL = process.env.REACT_APP_GIT_REPOSITORY_URL;

export const QUESTION_SIZE = 8;

export const SVG_WIDTH = 724;
export const SVG_HEIGHT = 500;

export const AUTOMATON_ANIMATION_DURATION = 1.4;

export const MAX_STATE_LENGTH = 6;
