# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      RDS_HOSTNAME: 127.0.0.1
      RDS_USERNAME: automaton
      RDS_PASSWORD: automaton
      RDS_DB_NAME: automaton
      RDS_PORT: 3307

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: ${{env.RDS_USERNAME}}
          MYSQL_PASSWORD: ${{env.RDS_PASSWORD}}
          MYSQL_DATABASE: ${{env.RDS_DB_NAME}}
        ports:
          - 3307:3306

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        python -m pipenv install --dev
    - name: Run test
      run: pipenv run test

